### ISSUE TITLE
Lost all snippets when upgraded to 2.0 version

### ISSUE THREAD

**Issue by saiballo** [tahabasri/snippets#31] opened 2021-07-25 10:55 UTC
With upgrade to 2.0 version I lost all my previous snippets...

**Comment by tahabasri** [comment] 2021-07-25 16:47
- what OS are you using ?
- did you get a popup with following content `You have some old snippets saved in <snippetsPath>, do you want to restore them ? (Original file will be removed).` ?

**Comment by saiballo** [comment] 2021-07-25 18:17
I'm on linux and I did get the popup. Indeed I click "restore". File was deleted but not imported

**Comment by tahabasri** [comment] 2021-07-26 01:29
I'll try to get access to a Linux machine in order to investigate, I tested the migration process multiple times because I know it's very frustrating to lose such data. I'll replace removing the old file with renaming it (adding `_bak` at the end for possible cases like this one). Apologies for the inconvenience, I hope you had a backup at least.

**Comment by saiballo** [comment] 2021-07-26 07:19
Your choice to rename the file is right.

I'm linux user... I have a backup of course :-)

**Comment by tahabasri** [comment] 2021-07-26 10:05
Just checked on a Linux machine with the updated version, I can successfully restore snippets. Can't reproduce. Thus, I just got my 1 star review on the market place for similar issue (understandable).

https://user-images.githubusercontent.com/12661966/126971383-15239cfb-b808-49b2-886f-7c127d92ab92.mov

**Comment by saiballo** [comment] 2021-07-26 10:08
I appreciate your job. I didn't give you 1 star.

**Comment by saiballo** [comment] 2021-07-26 10:10
I tried on a second LINUX machine. I can successfully restore snippets without problems. So I think is very specific issue, not frequent.

**Comment by tahabasri** [comment] 2021-07-26 10:13
> I appreciate your job. I didn't give you 1 star.

That was from another user and it's understandable as it may happen to more potential users.

> I tried on a second LINUX machine. I can successfully restore snippets without problems. So I think is very specific issue, not frequent.

That's helping, thanks ! Can you always reproduce such issue on the first Linux machine following steps bellow :
- clean all available snippets from Snippets view (backup first)
- put back backed up file in original location (on Linux will be `/home/<user>/.config/Code/User/globalStorage/tahabasri.snippets/data.json`)
- reload VSCode in order to re-trigger restore logic
- choose `Restore Data` in the shown popup.

**Comment by saiballo** [comment] 2021-07-26 10:17
I'll try as soon possible and give you a feedback

**Comment by banBanshie** [comment] 2021-07-26 19:43
I lost my Snippets on a windows machine like user 'saiballo'.
I got the notification notifying about successful import and deleting the old file but snippets was empty.
Luckly I didnt have too much and were easily recovered.

PS: I gave you five stars you deserve for this lovely job, I understand shit happens ;)

**Comment by tahabasri** [comment] 2021-07-26 22:18
@banBanshie I really appreciate your feedback. This is the first time that I see such case, literally took the time to test on all 3 platforms (Windows, MacOS and Linux) just to make sure that such thing don't happen. I'll wait for @saiballo feedback and I'll keep investigating.

**Comment by saiballo** [comment] 2021-07-27 07:15
It's very strange. I did the import twice and it did work. It may depends by a conflict with another extension? I don't know....

**Comment by tahabasri** [comment] 2021-07-27 09:25
Tried to simulate the upgrade process from scratch (install version `1.2.1` then upgrade to `2.0.1`) but migration works perfectly. I added more logic to :
- inform user before proceeding with restore
- keep backup of original snippets file
- check if restore worked once done and inform user of 'real' state

Pushed new [release 2.0.2](https://github.com/tahabasri/snippets/releases/tag/2.0.2). Will close this issue for now as I can't reproduce it. Anyone is welcome to reopen if he can reproduce multiple times with a clear set of steps.

Thanks @saiballo @banBanshie for the contribution 🙏🏼

**Closed by tahabasri** 2021-07-27 09:25 UTC
